sudo: required # is required to use docker service in travis
dist: xenial
language: node_js

services:
  - docker 

install:
  - docker --version  
  - pip install --user awscli 
  - export PATH=$PATH:$HOME/.local/bin
  - yes | sudo apt-get install jq

after_success:
  - if [[ $TRAVIS_BRANCH == 'develop' ]]; then eval $(aws ecr get-login --no-include-email --region us-west-1) && docker build -t geo-cache . && docker tag geo-cache:latest 341707006720.dkr.ecr.us-west-1.amazonaws.com/google-proxy:latest && docker push 341707006720.dkr.ecr.us-west-1.amazonaws.com/google-proxy:latest && chmod +x ./ecs-bin/ecs-deploy && ./ecs-bin/ecs-deploy -c google-proxy -n geocache -r us-west-1 -i 341707006720.dkr.ecr.us-west-1.amazonaws.com/google-proxy:latest; fi